name: PlatformIO Build

# Trigger the workflow on push and pull request events
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define the jobs
jobs:
  build:
    name: Build PlatformIO Project
    runs-on: ubuntu:24.04

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # Step 3: Install PlatformIO
      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install platformio

      # Step 4: Build the PlatformIO Project
      - name: Build Project
        run: |
          platformio run

      # Step 5: (Optional) Upload build artifacts
      - name: Upload Firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: .pio/build/**/*.{bin,elf,map}
